site_name: CIRASAME User Guide
site_description: CIRASAME User Guide
site_author: Ryotaro Honda
copyright: KEK IPNS
repo_url: https://github.com/spadi-alliance/ug-cirasame
repo_name: ug-cirasame

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
  palette:
    #scheme: slate
    scheme: default
    primary: lime

markdown_extensions:
  - attr_list
  - def_list
  - markdown_katex:
      no_inline_svg: true
      insert_fonts_css: true
  #  - hbfm.inline_coloring
  #  - hbfm.inline_list
  #  - toc:
  #      slugify: !!python/name:hbfm.toc.slugify
  #- hbfm.number_headers
  #- hbfm.quote_uri_hash
  - image_captions:
      numbering: true
  - caption:
      numbering: true

extra_css:
  - css/custom.css

nav:
  - Top: index.md
  - Release: release/release.md
  - Hardware:
      - CIRASAME: hardware/cirasame/cirasame.md
  - Firmware:
      - Skeleton: firmware/skeleton/skeleton.md
      - StrLRTDC: firmware/strlrtdc/strlrtdc.md
      - StrLRTDC-10G: firmware/strlrtdc-10g/strlrtdc-10g.md
  - Software: software/software.md
  - Practical Usage: practical/practical.md
